### ISSUE TITLE
Exception in OnVolumioStart can crash the whole UI

### ISSUE THREAD

**Issue by petecallaghan** [petecallaghan/volumio-plugins#23]
@petecallaghan please can you fix the plugin ASAP?
It makes the whole system fail.

Two suggestions:

Do not place anything in the onVolumioStart function, but put all on the onStart
Always use try catch when you execute
This is a report:
volumio/Volumio2-UI#801

To me, the issue starts at https://github.com/volumio/volumio-plugins/blob/b68938b929424e09796d61973af5220ea94e1a36/plugins/miscellanea/music_services_shield/index.js#L69

Example stack trace:

Oct 04 11:42:51 volumio sudo[1127]: pam_unix(sudo:session): session closed for user root
Oct 04 11:42:52 volumio volumio[1075]: info: Applying required configuration parameters for plugin music_services_shield
Oct 04 11:42:52 volumio volumio[1075]: /bin/sh: 1: /data/plugins/miscellanea/music_services_shield/setconfigparameter.sh: Perm
Oct 04 11:42:52 volumio volumio[1075]: child_process.js:644
Oct 04 11:42:52 volumio volumio[1075]: throw err;
Oct 04 11:42:52 volumio volumio[1075]: ^
Oct 04 11:42:52 volumio volumio[1075]: Error: Command failed: /data/plugins/miscellanea/music_services_shield/setconfigparamet
Oct 04 11:42:52 volumio volumio[1075]: /bin/sh: 1: /data/plugins/miscellanea/music_services_shield/setconfigparameter.sh: Perm
Oct 04 11:42:52 volumio volumio[1075]: at checkExecSyncError (child_process.js:601:13)
Oct 04 11:42:52 volumio volumio[1075]: at execSync (child_process.js:641:13)
Oct 04 11:42:52 volumio volumio[1075]: at musicServicesShield.writeConfigParameter (/data/plugins/miscellanea/music_services_s
Oct 04 11:42:52 volumio volumio[1075]: at musicServicesShield.writeAllConfigParameters (/data/plugins/miscellanea/music_servic
Oct 04 11:42:52 volumio volumio[1075]: at musicServicesShield.onVolumioStart (/data/plugins/miscellanea/music_services_shield/
Oct 04 11:42:52 volumio volumio[1075]: at PluginManager.loadCorePlugin (/volumio/app/pluginmanager.js:171:38)
Oct 04 11:42:52 volumio volumio[1075]: at /volumio/app/pluginmanager.js:250:34
Oct 04 11:42:52 volumio volumio[1075]: at Array.forEach ()
Oct 04 11:42:52 volumio volumio[1075]: at HashMap. (/volumio/app/pluginmanager.js:249:20)
Oct 04 11:42:52 volumio volumio[1075]: at HashMap.forEach (/volumio/node_modules/hashmap/hashmap.js:171:10)
Oct 04 11:42:52 volumio systemd[1]: volumio.service: main process exited, code=exited, status=1/FAILURE

**Comment by petecallaghan** [comment]
Duplicated by https://github.com/petecallaghan/volumio-plugins/issues/22
